version: '3'
services:
  a_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - kafka
    links:
      - mongo
      - kafka

  b_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    links:
      - kafka

  mongo:
    image: mongo

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
